name: Publish Page (codeberg)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: codeberg-small
    env: # https://forgejo.org/docs/v11.0/user/actions/reference/#secrets
      DISCORD_LINK: ${{ vars.DISCORD_LINK }}
      GIT_HASH: ${{ forge.sha }}
      GOOGLE_ANALYTICS_ID: ${{ vars.GOOGLE_ANALYTICS_ID }}
      SITE_URL: "https://${{ forge.repository_owner }}.codeberg.page"
      ETH_DONATION_ADDRESS: ${{ vars.ETH_DONATION_ADDRESS }}
      BTC_DONATION_ADDRESSES: ${{ secrets.BTC_DONATION_ADDRESSES }}
    steps:
      - name: Checkout repository
        uses: https://data.forgejo.org/actions/checkout@v6
      - name: Setup Node.js
        uses: https://data.forgejo.org/actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: Enable Corepack and Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Deploy page
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: ${{ env.SITE_URL }}
          token: ${{ forge.token }}
          source: ./build
