name: "Inspect PR"

on:
  pull_request:
  workflow_dispatch:

jobs:
  inspect-pr:
    runs-on: ubuntu-latest
    env:
      DISCORD_LINK: ${{ vars.DISCORD_LINK }}
      GITHUB_SHA: ${{ github.sha }}
      GOOGLE_ANALYTICS_ID: ${{ vars.GOOGLE_ANALYTICS_ID }}
      RAIN_GITHUB_IO: "https://${{ github.repository_owner }}.github.io"
    # TODO: consider adding a `fail-fast` strategy?
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup PNPM
        uses: pnpm/action-setup@v6
        with:
          version: 11
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Spell checking
        run: pnpm run spellcheck
        # uses: streetsidesoftware/cspell-action@v8
      - name: Type checking
        run: pnpm run typecheck
      - name: Code linting
        run: pnpm run lint
      - name: Tests
        run: pnpm run test
      - name: Try build project
        run: pnpm run build
